"""add field username to student model

Revision ID: 7ea5afb2d922
Revises: 88a6a303de8c
Create Date: 2025-08-26 13:33:08.547483

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7ea5afb2d922"
down_revision: Union[str, None] = "88a6a303de8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "students", sa.Column("username", sa.String(), nullable=False)
    )
    op.create_unique_constraint(None, "students", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "students", type_="unique")
    op.drop_column("students", "username")
    # ### end Alembic commands ###
